image: rootproject/root-cc7

stages: 
    - build

deployment:
    stage: build

    before_script:     #Set up root and dependancies     
        # - . /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.14.02/x86_64-fedora28-gcc81-opt/root/bin/thisroot.sh
        - . /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.18.04/x86_64-centos7-gcc48-opt/bin/thisroot.sh
        - . /cvmfs/geant4.cern.ch/geant4/10.5.p01/x86_64-centos7-gcc8-opt-MT/bin/geant4.sh

    script:
        - echo "Building"
        - rm -rf build
        - mkdir build
        - cd build
        - cmake3 .. -DCMAKE_INSTALL_PREFIX=..
        - cmake3 --build . --target install

     