image: rootproject/root-cc7

stages: 
    - build

deployment:
    stage: build

    before_script:
        - . /opt/rh/devtoolset-8/enable
        - yum install -y cmake3.x86_64
        - yum install -y motif-devel.x86_64

    script:
        - . /opt/rh/devtoolset-8/enable
        - . /cvmfs/geant4.cern.ch/geant4/10.5.p01/x86_64-centos7-gcc8-opt/bin/geant4.sh
        - head -4 /cvmfs/geant4.cern.ch/geant4/10.5.p01/x86_64-centos7-gcc8-opt/bin/geant4.sh | tail -1
        - mkdir build
        - cd build
        - cmake3 .. -DCMAKE_INSTALL_PREFIX=..
        - cmake3 --build . --target install
